# Generated by Django 5.2.3 on 2025-06-29 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('politics', 'Politics'), ('world-all', 'World'), ('opinion-all', 'Opinion'), ('crime-bangladesh', 'Crime Bangladesh'), ('business-all', 'Business'), ('sports-all', 'Sports'), ('entertainment-all', 'Entertainment'), ('chakri-all', 'Jobs'), ('lifestyle-all', 'Lifestyle')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=20)),
                ('max_pages', models.IntegerField(default=2)),
                ('total_articles', models.IntegerField(default=0)),
                ('scraped_articles', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
