# Generated by Django 5.2.3 on 2025-06-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='s3_key',
            field=models.CharField(blank=True, help_text='S3 key/path for the zip file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scrapingtask',
            name='s3_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapingtask',
            name='s3_url',
            field=models.URLField(blank=True, help_text='S3 URL where the zip file is stored', null=True),
        ),
    ]
